ImportError: cannot import name 'log_error' from partially initialized module 'main' (most likely due to a circular import) - refactor runtime.py into main